import type { BinaryLoad, MachineIR } from "@typenode/core";

export interface RescOptions {
  replPath: string;
  machineName?: string;
}

export function emitResc(machine: MachineIR, opts: RescOptions): string {
  const name = opts.machineName ?? machine.name;
  const lines: string[] = [
    `:name: ${name}`,
    `:description: Generated by TypeNode`,
    ``,
    `mach create "${name}"`,
    `machine LoadPlatformDescription @${opts.replPath}`,
    ``,
  ];

  if (machine.scripts.preInit.length > 0) {
    for (const cmd of machine.scripts.preInit) lines.push(cmd);
    lines.push("");
  }

  for (const bin of machine.scripts.binaries) {
    lines.push(loadBinary(bin));
  }
  if (machine.scripts.binaries.length > 0) lines.push("");

  for (const cmd of machine.scripts.init) lines.push(cmd);
  if (machine.scripts.init.length > 0) lines.push("");

  if (machine.scripts.start) {
    lines.push("start");
  }

  for (const cmd of machine.scripts.postInit) lines.push(cmd);

  return lines.join("\n").trimEnd() + "\n";
}

function loadBinary(bin: BinaryLoad): string {
  const target = bin.cpu ? `${bin.cpu} ` : "sysbus ";
  switch (bin.format) {
    case "elf":
      return `${target}LoadELF @${bin.path}`;
    case "hex":
      return `${target}LoadHEX @${bin.path}`;
    case "binary":
      if (bin.address === undefined) {
        throw new Error("binary format requires an address");
      }
      return `${target}LoadBinary @${bin.path} 0x${bin.address.toString(16)}`;
  }
}
